"""
Pendo Essence - Sample Data Population Script
Run with: python manage.py shell < populate_sample_data.py
Or copy-paste into: python manage.py shell
"""

import os
import django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'pendo_essence.settings')
django.setup()

from store.models import Category, Product

print(">>> Starting Pendo Essence data population...")

# ─────────────────────────────────────────
# CATEGORIES
# ─────────────────────────────────────────
categories_data = [
    {
        'name': 'Cleansers',
        'slug': 'cleansers',
        'description': 'Gentle yet effective cleansers to remove impurities, makeup, and excess oil without stripping your skin.',
        'icon': 'fa-soap',
        'order': 1,
    },
    {
        'name': 'Toners',
        'slug': 'toners',
        'description': 'Balancing toners that hydrate, minimize pores, and prep your skin for the next steps in your routine.',
        'icon': 'fa-tint',
        'order': 2,
    },
    {
        'name': 'Serums',
        'slug': 'serums',
        'description': 'Potent serums packed with active ingredients targeting specific skin concerns.',
        'icon': 'fa-flask',
        'order': 3,
    },
    {
        'name': 'Moisturisers',
        'slug': 'moisturisers',
        'description': 'Nourishing moisturisers to lock in hydration and keep your skin soft and supple all day.',
        'icon': 'fa-droplet',
        'order': 4,
    },
    {
        'name': 'Sunscreen',
        'slug': 'sunscreen',
        'description': 'Broad-spectrum sun protection to shield your skin from harmful UV rays every single day.',
        'icon': 'fa-sun',
        'order': 5,
    },
    {
        'name': 'Eye Care',
        'slug': 'eye-care',
        'description': 'Targeted eye creams and gels to address dark circles, puffiness, and fine lines around the eyes.',
        'icon': 'fa-eye',
        'order': 6,
    },
    {
        'name': 'Masks & Treatments',
        'slug': 'masks-treatments',
        'description': 'Weekly masks and intensive treatments to give your skin a deep reset and targeted care.',
        'icon': 'fa-star',
        'order': 7,
    },
    {
        'name': 'Lip Care',
        'slug': 'lip-care',
        'description': 'Nourishing lip balms, scrubs, and treatments for soft, healthy, hydrated lips.',
        'icon': 'fa-kiss',
        'order': 8,
    },
    {
        'name': 'Hair Care',
        'slug': 'hair-care',
        'description': 'Natural hair care products to cleanse, nourish, and strengthen your hair from root to tip.',
        'icon': 'fa-spa',
        'order': 9,
    },
    {
        'name': 'Body Care',
        'slug': 'body-care',
        'description': 'Luxurious body lotions, oils, and scrubs for silky smooth skin from head to toe.',
        'icon': 'fa-heart',
        'order': 10,
    },
    {
        'name': 'Deodorants',
        'slug': 'deodorants',
        'description': 'Natural, aluminium-free deodorants that keep you fresh without harsh chemicals.',
        'icon': 'fa-wind',
        'order': 11,
    },
    {
        'name': 'Oils & Elixirs',
        'slug': 'oils-elixirs',
        'description': 'Pure face and body oils for deep nourishment, glow, and radiant skin.',
        'icon': 'fa-leaf',
        'order': 12,
    },
]

print(">>> Creating categories...")
created_cats = {}
for cat_data in categories_data:
    cat, created = Category.objects.get_or_create(
        slug=cat_data['slug'],
        defaults=cat_data
    )
    created_cats[cat_data['slug']] = cat
    status = "[CREATED]" if created else "[EXISTS] "
    print(f"  {status}: {cat.name}")

print(f"\n>>> {len(created_cats)} categories ready!\n")


# ─────────────────────────────────────────
# PRODUCTS
# ─────────────────────────────────────────
products_data = [

    # ── CLEANSERS ──
    {
        'category_slug': 'cleansers',
        'name': 'Rose Petal Gentle Foam Cleanser',
        'brand': 'Pendo Essence',
        'description': 'A luxuriously soft foaming cleanser infused with real rose petal extract and aloe vera. This gentle formula melts away makeup, dirt, and excess oil while maintaining your skin\'s natural moisture barrier. Suitable for daily use morning and night.',
        'short_description': 'Soft foaming cleanser with rose & aloe vera for all skin types.',
        'ingredients': 'Aqua, Rose Petal Extract, Aloe Barbadensis Leaf Juice, Glycerin, Sodium Cocoyl Isethionate, Panthenol, Allantoin, Citric Acid, Phenoxyethanol.',
        'how_to_use': 'Wet face with lukewarm water. Dispense a small amount onto palms and lather. Gently massage onto face in circular motions for 30-60 seconds. Rinse thoroughly and pat dry.',
        'benefits': 'Removes makeup and impurities\nMaintains skin moisture barrier\nCalms redness and irritation\nLeaves skin soft and refreshed\npH balanced formula',
        'skin_type': 'all',
        'size': '150ml',
        'price': '24500.00',
        'compare_price': '30000.00',
        'stock': 85,
        'is_featured': True,
        'is_bestseller': True,
        'is_natural': True,
        'slug': 'rose-petal-gentle-foam-cleanser-150ml',
    },
    {
        'category_slug': 'cleansers',
        'name': 'Charcoal Deep Pore Cleanser',
        'brand': 'Pendo Essence',
        'description': 'Activated charcoal meets tea tree oil in this powerful yet gentle pore-clearing cleanser. Draws out toxins, unclogs pores, and controls excess oil without over-drying. Perfect for oily and acne-prone skin types.',
        'short_description': 'Activated charcoal cleanser that unclogs pores and controls oil.',
        'ingredients': 'Aqua, Activated Charcoal Powder, Tea Tree Leaf Oil, Glycerin, Sodium Cocoyl Glutamate, Zinc PCA, Niacinamide, Panthenol, Salicylic Acid, Phenoxyethanol.',
        'how_to_use': 'Apply to damp skin and massage in circular motions for 60 seconds. Focus on T-zone and congested areas. Rinse thoroughly with warm water. Use once or twice daily.',
        'benefits': 'Deep cleanses pores\nControls excess sebum\nReduces blackheads\nAntibacterial properties\nMatte finish after use',
        'skin_type': 'oily',
        'size': '120ml',
        'price': '28000.00',
        'compare_price': '34000.00',
        'stock': 60,
        'is_featured': False,
        'is_bestseller': True,
        'is_natural': True,
        'slug': 'charcoal-deep-pore-cleanser-120ml',
    },
    {
        'category_slug': 'cleansers',
        'name': 'Oat & Honey Cream Cleanser',
        'brand': 'Pendo Essence',
        'description': 'An ultra-gentle cream cleanser specially formulated for dry and sensitive skin. Colloidal oatmeal and raw honey extract soothe irritation while nourishing the skin. Zero lather, maximum comfort.',
        'short_description': 'Ultra-soothing cream cleanser with oat & honey for sensitive skin.',
        'ingredients': 'Aqua, Colloidal Oatmeal, Honey Extract, Shea Butter, Glycerin, Ceramide NP, Centella Asiatica, Bisabolol, Allantoin, Phenoxyethanol.',
        'how_to_use': 'Apply to dry or damp skin. Massage gently in upward circular motions. Remove with a damp cloth or rinse with lukewarm water. Can be used as a makeup remover.',
        'benefits': 'Calms sensitive and reactive skin\nRepairs damaged moisture barrier\nNo foam, no stripping\nRelieves dryness and flaking\nSafe for eczema-prone skin',
        'skin_type': 'sensitive',
        'size': '200ml',
        'price': '26500.00',
        'compare_price': None,
        'stock': 45,
        'is_featured': True,
        'is_new_arrival': True,
        'is_natural': True,
        'slug': 'oat-honey-cream-cleanser-200ml',
    },
    {
        'category_slug': 'cleansers',
        'name': 'Green Tea Micellar Cleansing Water',
        'brand': 'Pendo Essence',
        'description': 'No-rinse micellar water enriched with green tea antioxidants and hyaluronic acid. Effortlessly removes makeup, sunscreen, and daily grime with just a cotton pad. Leaves skin feeling clean, hydrated, and fresh.',
        'short_description': 'Antioxidant-rich micellar water with green tea & hyaluronic acid.',
        'ingredients': 'Aqua, Micelles, Camellia Sinensis Leaf Extract, Sodium Hyaluronate, Glycerin, Niacinamide, Panthenol, Allantoin.',
        'how_to_use': 'Pour onto a cotton pad and sweep gently across face, eyes, and lips. No rinsing required. Use morning and evening as first cleansing step.',
        'benefits': 'Removes waterproof makeup\nZero irritation formula\nHydrates while cleansing\nAntioxidant protection\nNo rinse needed',
        'skin_type': 'all',
        'size': '250ml',
        'price': '22000.00',
        'compare_price': '27000.00',
        'stock': 100,
        'is_bestseller': True,
        'is_natural': True,
        'slug': 'green-tea-micellar-cleansing-water-250ml',
    },
    {
        'category_slug': 'cleansers',
        'name': 'Papaya Enzyme Exfoliating Gel Cleanser',
        'brand': 'Pendo Essence',
        'description': 'A unique gel-to-foam cleanser powered by natural papaya enzymes that gently dissolve dead skin cells while cleansing. Reveals brighter, smoother skin with every wash. No harsh physical scrubbing required.',
        'short_description': 'Enzymatic gel cleanser with papaya for gentle daily exfoliation.',
        'ingredients': 'Aqua, Papain (Papaya Enzyme), Glycerin, Sodium Cocoyl Glutamate, Vitamin C, Kojic Acid, Lactic Acid, Aloe Vera, Phenoxyethanol.',
        'how_to_use': 'Apply to damp skin, massage for 60-90 seconds to activate enzymes. Rinse thoroughly. Use in the evening. Follow with sunscreen in the morning.',
        'benefits': 'Gentle enzymatic exfoliation\nBrightens dull complexion\nEven skin tone\nNo physical microbeads\nUnclogs pores naturally',
        'skin_type': 'combination',
        'size': '130ml',
        'price': '31000.00',
        'compare_price': '38000.00',
        'stock': 38,
        'is_new_arrival': True,
        'is_natural': True,
        'slug': 'papaya-enzyme-exfoliating-gel-cleanser-130ml',
    },

    # ── TONERS ──
    {
        'category_slug': 'toners',
        'name': 'Rosewater & Niacinamide Brightening Toner',
        'brand': 'Pendo Essence',
        'description': 'A refreshing toner that combines the timeless benefits of pure rosewater with 5% niacinamide to brighten, balance, and prep the skin for serums. Minimizes the appearance of pores and controls shine throughout the day.',
        'short_description': 'Brightening toner with rosewater & 5% niacinamide for radiant skin.',
        'ingredients': 'Rosa Damascena Flower Water, Niacinamide, Sodium Hyaluronate, Glycerin, Zinc PCA, Panthenol, Allantoin, Phenoxyethanol.',
        'how_to_use': 'After cleansing, pour a small amount onto a cotton pad or palm. Gently sweep or pat across face and neck. Follow with serum and moisturiser.',
        'benefits': 'Minimizes pore appearance\nBrightens uneven skin tone\nBalances excess oil\nHydrates and refreshes\nPreps skin for next steps',
        'skin_type': 'combination',
        'size': '200ml',
        'price': '27000.00',
        'compare_price': '33000.00',
        'stock': 75,
        'is_featured': True,
        'is_bestseller': True,
        'is_natural': True,
        'slug': 'rosewater-niacinamide-brightening-toner-200ml',
    },
    {
        'category_slug': 'toners',
        'name': 'Centella Asiatica Calming Essence Toner',
        'brand': 'Pendo Essence',
        'description': 'A soothing essence-toner hybrid featuring 70% centella asiatica extract to calm inflammation, strengthen the skin barrier, and speed up skin healing. The watery texture layers effortlessly for intense hydration.',
        'short_description': '70% cica essence toner to calm, heal, and strengthen the skin barrier.',
        'ingredients': 'Centella Asiatica Extract 70%, Aqua, Glycerin, Sodium Hyaluronate, Beta-Glucan, Panthenol, Madecassoside, Asiaticoside, Allantoin.',
        'how_to_use': 'Apply 2-3 layers onto cleansed skin using the 7-skin method or pat gently until absorbed. Use morning and evening.',
        'benefits': 'Reduces redness and inflammation\nRepairs compromised barrier\nSpeeds up wound healing\nDeep multi-layer hydration\nIdeal post-procedure skin',
        'skin_type': 'sensitive',
        'size': '150ml',
        'price': '32000.00',
        'compare_price': None,
        'stock': 50,
        'is_new_arrival': True,
        'is_natural': True,
        'slug': 'centella-asiatica-calming-essence-toner-150ml',
    },
    {
        'category_slug': 'toners',
        'name': 'AHA BHA Exfoliating Clarifying Toner',
        'brand': 'Pendo Essence',
        'description': 'A chemical exfoliant toner with glycolic acid (AHA) and salicylic acid (BHA) to slough off dead skin cells, unclog pores, and prevent breakouts. Reveals smoother, clearer skin over time without the need for manual scrubbing.',
        'short_description': 'Dual-acid exfoliating toner for smoother, clearer, breakout-free skin.',
        'ingredients': 'Aqua, Glycolic Acid 5%, Salicylic Acid 0.5%, Witch Hazel, Niacinamide, Glycerin, Aloe Vera, Allantoin, Phenoxyethanol.',
        'how_to_use': 'Apply to a cotton pad and sweep across cleansed face, avoiding eye area. Use every other night initially, building up to nightly use. Always use SPF in the morning.',
        'benefits': 'Exfoliates without scrubbing\nUnclogs and minimizes pores\nPrevents and treats acne\nSmooths rough skin texture\nFades post-acne marks',
        'skin_type': 'acne_prone',
        'size': '120ml',
        'price': '29500.00',
        'compare_price': '36000.00',
        'stock': 65,
        'is_bestseller': True,
        'is_natural': False,
        'slug': 'aha-bha-exfoliating-clarifying-toner-120ml',
    },

    # ── SERUMS ──
    {
        'category_slug': 'serums',
        'name': 'Vitamin C 15% Brightening Radiance Serum',
        'brand': 'Pendo Essence',
        'description': 'Our cult-favourite Vitamin C serum formulated with 15% stabilized L-Ascorbic Acid, Vitamin E, and Ferulic Acid for maximum antioxidant protection and brightening power. Fades dark spots, evens skin tone, and boosts collagen production for firmer, more radiant skin.',
        'short_description': '15% Vitamin C + Vitamin E + Ferulic Acid for maximum brightening power.',
        'ingredients': 'Aqua, L-Ascorbic Acid 15%, Tocopherol (Vitamin E), Ferulic Acid, Niacinamide, Hyaluronic Acid, Glycerin, Panthenol, Allantoin.',
        'how_to_use': 'Apply 3-4 drops to cleansed face every morning before moisturiser and sunscreen. Avoid mixing with Retinol in the same routine. Store in a cool, dark place.',
        'benefits': 'Fades dark spots and hyperpigmentation\nBoosts collagen production\nNeutralizes free radical damage\nBrightens dull complexion\nEven skin tone in 4-6 weeks',
        'skin_type': 'all',
        'size': '30ml',
        'price': '45000.00',
        'compare_price': '56000.00',
        'stock': 55,
        'is_featured': True,
        'is_bestseller': True,
        'is_natural': True,
        'slug': 'vitamin-c-15-brightening-radiance-serum-30ml',
    },
    {
        'category_slug': 'serums',
        'name': 'Retinol 0.3% Anti-Ageing Night Serum',
        'brand': 'Pendo Essence',
        'description': 'A beginner-friendly retinol serum at 0.3% concentration, encapsulated for slow release to minimize irritation. Visibly reduces fine lines, wrinkles, and uneven texture overnight. Buffered with squalane and ceramides for a comfortable experience.',
        'short_description': 'Encapsulated retinol 0.3% serum for smooth, firm, youthful skin.',
        'ingredients': 'Aqua, Encapsulated Retinol 0.3%, Squalane, Ceramide NP, Niacinamide, Glycerin, Peptide Complex, Allantoin, Phenoxyethanol.',
        'how_to_use': 'Apply 2-3 drops to cleansed skin on nights only. Start with 2x per week and gradually increase. Always follow with moisturiser. Always use SPF the next morning.',
        'benefits': 'Reduces fine lines and wrinkles\nSmooths rough skin texture\nFades acne scars\nFirmer, bouncier skin\nEncapsulated for reduced irritation',
        'skin_type': 'normal',
        'size': '30ml',
        'price': '52000.00',
        'compare_price': '65000.00',
        'stock': 40,
        'is_featured': True,
        'is_new_arrival': False,
        'is_natural': True,
        'slug': 'retinol-03-anti-ageing-night-serum-30ml',
    },
    {
        'category_slug': 'serums',
        'name': 'Hyaluronic Acid + Peptide Hydration Serum',
        'brand': 'Pendo Essence',
        'description': 'A lightweight plumping serum with three molecular weights of hyaluronic acid (high, medium, and low) to hydrate at every layer of the skin, combined with a peptide complex that supports collagen and elastin production.',
        'short_description': 'Triple-weight HA + peptide serum for deep, lasting plump hydration.',
        'ingredients': 'Aqua, Sodium Hyaluronate (3 Molecular Weights), Argireline, Matrixyl 3000, Glycerin, Beta-Glucan, Panthenol, Allantoin, Phenoxyethanol.',
        'how_to_use': 'Apply 3-4 drops to damp skin after toner, morning and evening. Pat gently until absorbed. Follow with moisturiser to lock in hydration.',
        'benefits': 'Plumps dehydrated skin instantly\nHydrates at all skin layers\nReduces fine lines caused by dryness\nFirming peptide action\nUniversal — safe in any routine',
        'skin_type': 'dry',
        'size': '30ml',
        'price': '38500.00',
        'compare_price': '47000.00',
        'stock': 80,
        'is_featured': False,
        'is_bestseller': True,
        'is_natural': True,
        'slug': 'hyaluronic-acid-peptide-hydration-serum-30ml',
    },
    {
        'category_slug': 'serums',
        'name': 'Niacinamide 10% + Zinc Pore Refining Serum',
        'brand': 'Pendo Essence',
        'description': 'A targeted serum with 10% niacinamide and 1% zinc PCA to visibly minimize pores, regulate sebum, fade blemishes, and strengthen the skin barrier. One of the most versatile serums in any skincare routine.',
        'short_description': '10% Niacinamide + Zinc to minimize pores, control oil, and clear skin.',
        'ingredients': 'Aqua, Niacinamide 10%, Zinc PCA 1%, Hyaluronic Acid, Glycerin, Panthenol, Allantoin, Phenoxyethanol.',
        'how_to_use': 'Apply 2-3 drops to cleansed skin, morning and/or evening. Can be layered under moisturiser and sunscreen. Avoid combining with Vitamin C at the same time.',
        'benefits': 'Minimizes enlarged pores\nControls and balances sebum\nFades dark spots and acne marks\nStrengthens skin barrier\nBrightens dull skin tone',
        'skin_type': 'oily',
        'size': '30ml',
        'price': '34000.00',
        'compare_price': '42000.00',
        'stock': 90,
        'is_bestseller': True,
        'is_natural': True,
        'slug': 'niacinamide-10-zinc-pore-refining-serum-30ml',
    },
    {
        'category_slug': 'serums',
        'name': 'Bakuchiol Plant Retinol Gentle Serum',
        'brand': 'Pendo Essence',
        'description': 'The natural, pregnancy-safe alternative to retinol. Bakuchiol, derived from the babchi plant, delivers retinol-like benefits — reduced fine lines, improved firmness, and even skin tone — without the irritation, peeling, or sun sensitivity.',
        'short_description': 'Natural bakuchiol serum — all retinol benefits, zero irritation.',
        'ingredients': 'Aqua, Bakuchiol 1%, Rosehip Seed Oil, Squalane, Jojoba Oil, Sea Buckthorn Extract, Vitamin E, Glycerin, Phenoxyethanol.',
        'how_to_use': 'Apply 3-4 drops morning and/or evening to cleansed skin. Suitable for pregnant and breastfeeding women. Can be used with other actives without concern.',
        'benefits': 'Retinol-like results without irritation\nSafe for sensitive and pregnant skin\nFirms and plumps skin\nFades fine lines naturally\nNo photosensitivity',
        'skin_type': 'sensitive',
        'size': '30ml',
        'price': '41000.00',
        'compare_price': '50000.00',
        'stock': 30,
        'is_new_arrival': True,
        'is_featured': True,
        'is_natural': True,
        'slug': 'bakuchiol-plant-retinol-gentle-serum-30ml',
    },

    # ── MOISTURISERS ──
    {
        'category_slug': 'moisturisers',
        'name': 'Shea & Ceramide Rich Barrier Cream',
        'brand': 'Pendo Essence',
        'description': 'A deeply nourishing barrier repair cream formulated with shea butter, ceramides, and cholesterol to restore and strengthen the skin\'s natural protective layer. Perfect for very dry, dehydrated, or compromised skin that needs serious moisture replenishment.',
        'short_description': 'Rich barrier cream with shea, ceramides & cholesterol for very dry skin.',
        'ingredients': 'Aqua, Shea Butter, Ceramide NP, Ceramide AP, Cholesterol, Glycerin, Squalane, Niacinamide, Allantoin, Phenoxyethanol.',
        'how_to_use': 'Apply generously to face and neck as last step in skincare routine, morning and evening. Can also be used on hands, elbows, and heels.',
        'benefits': 'Repairs damaged skin barrier\nProvides 72-hour hydration\nReduces transepidermal water loss\nSoothes redness and irritation\nNon-greasy despite richness',
        'skin_type': 'dry',
        'size': '50ml',
        'price': '36000.00',
        'compare_price': '44000.00',
        'stock': 55,
        'is_featured': True,
        'is_bestseller': True,
        'is_natural': True,
        'slug': 'shea-ceramide-rich-barrier-cream-50ml',
    },
    {
        'category_slug': 'moisturisers',
        'name': 'Oil-Free Hydrating Gel Moisturiser',
        'brand': 'Pendo Essence',
        'description': 'A featherlight, oil-free gel moisturiser that delivers powerful hydration without any heaviness or shine. Formulated with hyaluronic acid, aloe vera, and green tea extract. Your skin drinks it up in seconds.',
        'short_description': 'Lightweight oil-free gel that hydrates without clogging pores.',
        'ingredients': 'Aqua, Aloe Barbadensis Leaf Juice, Hyaluronic Acid, Niacinamide, Camellia Sinensis Extract, Glycerin, Allantoin, Panthenol, Phenoxyethanol.',
        'how_to_use': 'Apply a pea-sized amount to cleansed and toned skin. Massage in upward strokes until fully absorbed. Can be used under makeup as a primer base.',
        'benefits': 'Oil-free, non-comedogenic\nInstant cooling hydration\nMatte finish\nIdeal under SPF and makeup\nWon\'t clog pores',
        'skin_type': 'oily',
        'size': '50ml',
        'price': '29000.00',
        'compare_price': '36000.00',
        'stock': 70,
        'is_bestseller': True,
        'is_natural': True,
        'slug': 'oil-free-hydrating-gel-moisturiser-50ml',
    },
    {
        'category_slug': 'moisturisers',
        'name': 'Aloe Vera & Cucumber Soothing Day Cream',
        'brand': 'Pendo Essence',
        'description': 'A light, refreshing day cream perfect for combination skin. Aloe vera and cucumber extract calm irritation and provide hydration while a blend of antioxidants protects against environmental stressors throughout the day.',
        'short_description': 'Light day cream with aloe & cucumber to soothe and protect.',
        'ingredients': 'Aqua, Aloe Barbadensis Leaf Juice, Cucumber Extract, Glycerin, Niacinamide, Green Tea Extract, Panthenol, Ceramide NP, Phenoxyethanol.',
        'how_to_use': 'Apply every morning after toner and serum. Massage in upward circular motions. Follow with SPF for full daytime protection.',
        'benefits': 'Instantly soothes irritated skin\nLightweight and breathable\nAntioxidant-rich formula\nNon-greasy finish\nHydrates combination skin perfectly',
        'skin_type': 'combination',
        'size': '50ml',
        'price': '27500.00',
        'compare_price': None,
        'stock': 60,
        'is_new_arrival': True,
        'is_natural': True,
        'slug': 'aloe-vera-cucumber-soothing-day-cream-50ml',
    },
    {
        'category_slug': 'moisturisers',
        'name': 'Avocado & Marula Night Recovery Cream',
        'brand': 'Pendo Essence',
        'description': 'A rich nighttime repair cream that works in harmony with your skin\'s nocturnal renewal cycle. Avocado oil, marula oil, and a peptide complex deeply nourish, regenerate, and firm the skin while you sleep, so you wake up to visibly plumper, smoother skin.',
        'short_description': 'Rich night cream with avocado, marula & peptides for overnight renewal.',
        'ingredients': 'Aqua, Avocado Oil, Marula Oil, Glycerin, Peptide Complex, Shea Butter, Ceramide NP, Retinyl Palmitate, Squalane, Phenoxyethanol.',
        'how_to_use': 'Apply generously to face and neck every evening as the last step. Gently massage in upward strokes. For best results, use after Vitamin C or Retinol serum.',
        'benefits': 'Intense overnight repair\nPlumps fine lines by morning\nDeep nourishment and glow\nPeptide firming action\nNon-clogging despite richness',
        'skin_type': 'dry',
        'size': '50ml',
        'price': '42000.00',
        'compare_price': '52000.00',
        'stock': 45,
        'is_featured': True,
        'is_natural': True,
        'slug': 'avocado-marula-night-recovery-cream-50ml',
    },

    # ── SUNSCREEN ──
    {
        'category_slug': 'sunscreen',
        'name': 'SPF 50+ Invisible Sunscreen Fluid',
        'brand': 'Pendo Essence',
        'description': 'A next-generation broad-spectrum SPF 50+ sunscreen that disappears into all skin tones with zero white cast. Protects against UVA, UVB, and blue light while providing a moisturising, silky base for makeup. Water resistant up to 40 minutes.',
        'short_description': 'SPF 50+ with no white cast, blue light protection, water-resistant.',
        'ingredients': 'Aqua, Zinc Oxide, Titanium Dioxide, Niacinamide, Hyaluronic Acid, Glycerin, Vitamin E, Panthenol, Allantoin.',
        'how_to_use': 'Apply generously as the final step of your morning skincare routine. Reapply every 2 hours when outdoors. 1/4 teaspoon recommended for the face.',
        'benefits': 'Broad-spectrum UVA/UVB protection\nZero white cast formula\nBlue light defence\nWater-resistant\nSkin-friendly with niacinamide',
        'skin_type': 'all',
        'size': '50ml',
        'price': '35000.00',
        'compare_price': '43000.00',
        'stock': 95,
        'is_featured': True,
        'is_bestseller': True,
        'is_natural': True,
        'slug': 'spf-50-invisible-sunscreen-fluid-50ml',
    },
    {
        'category_slug': 'sunscreen',
        'name': 'SPF 30 Tinted Moisturising Sunscreen',
        'brand': 'Pendo Essence',
        'description': 'A beautiful 3-in-1 product combining SPF 30 protection, lightweight hydration, and a natural tint that evens out the skin tone. Available in universal tan shade that adapts to most complexions. Perfect for a no-makeup makeup look.',
        'short_description': 'SPF 30 with a natural tint for everyday easy sun protection & coverage.',
        'ingredients': 'Aqua, Zinc Oxide, Iron Oxides, Glycerin, Hyaluronic Acid, Niacinamide, Shea Butter, Vitamin E, Phenoxyethanol.',
        'how_to_use': 'Apply as last morning skincare step. Blend evenly across face and neck. Reapply every 2 hours in direct sunlight. Can be worn alone or under foundation.',
        'benefits': '3-in-1: SPF, tint, and hydration\nEvens skin tone naturally\nIron oxide for visible light protection\nLightweight and comfortable\nNo separate moisturiser needed',
        'skin_type': 'normal',
        'size': '40ml',
        'price': '38000.00',
        'compare_price': '46000.00',
        'stock': 50,
        'is_new_arrival': True,
        'is_natural': True,
        'slug': 'spf-30-tinted-moisturising-sunscreen-40ml',
    },

    # ── EYE CARE ──
    {
        'category_slug': 'eye-care',
        'name': 'Caffeine & Peptide Eye Depuff Gel',
        'brand': 'Pendo Essence',
        'description': 'Wake up your eyes with this cooling eye gel formulated with 5% caffeine solution and a peptide complex. Visibly reduces puffiness and dark circles in just minutes. The cooling metal tip applicator massages and drains fluid buildup instantly.',
        'short_description': 'Caffeine + peptide eye gel for puffiness, dark circles & fine lines.',
        'ingredients': 'Aqua, Caffeine 5%, Argireline, Matrixyl, Hyaluronic Acid, Vitamin K, Niacinamide, Aloe Vera, Allantoin, Phenoxyethanol.',
        'how_to_use': 'Apply a small amount around the orbital bone using ring finger tapping motions, morning and evening. Can be stored in the refrigerator for extra cooling effect.',
        'benefits': 'Reduces puffiness and bags\nLightens dark circles\nSmooths crow\'s feet\nInstant cooling and refreshing\nSuitable for contact lens wearers',
        'skin_type': 'all',
        'size': '15ml',
        'price': '39000.00',
        'compare_price': '48000.00',
        'stock': 42,
        'is_featured': True,
        'is_bestseller': True,
        'is_natural': True,
        'slug': 'caffeine-peptide-eye-depuff-gel-15ml',
    },
    {
        'category_slug': 'eye-care',
        'name': 'Retinol Eye Renewal Cream',
        'brand': 'Pendo Essence',
        'description': 'A specialized low-dose retinol eye cream designed for the delicate eye area. Gently resurfaces, firms, and reduces the appearance of fine lines and wrinkles around the eyes without irritation. Fortified with ceramides and peptides.',
        'short_description': 'Gentle retinol eye cream for firming, renewal, and wrinkle reduction.',
        'ingredients': 'Aqua, Retinyl Palmitate, Ceramide NP, Peptide Complex, Squalane, Shea Butter, Hyaluronic Acid, Allantoin, Vitamin E, Phenoxyethanol.',
        'how_to_use': 'Apply a tiny amount (rice grain size) around the eye area at night only. Tap gently with ring finger. Avoid direct contact with eyes. Use SPF next morning.',
        'benefits': 'Reduces fine lines around eyes\nFirms and lifts eye area\nGentle enough for eye skin\nCeramide barrier protection\nLong-term anti-ageing results',
        'skin_type': 'normal',
        'size': '15ml',
        'price': '44000.00',
        'compare_price': '55000.00',
        'stock': 28,
        'is_natural': True,
        'slug': 'retinol-eye-renewal-cream-15ml',
    },

    # ── MASKS & TREATMENTS ──
    {
        'category_slug': 'masks-treatments',
        'name': 'Kaolin Clay & Turmeric Purifying Mask',
        'brand': 'Pendo Essence',
        'description': 'A detoxifying clay mask combining white kaolin clay with turmeric and tea tree oil to absorb excess sebum, draw out pore-clogging impurities, and reduce inflammation. Leaves skin visibly cleaner, tighter, and brighter after just 15 minutes.',
        'short_description': 'Kaolin clay + turmeric mask to detox pores, control oil & brighten.',
        'ingredients': 'Kaolin Clay, Aqua, Turmeric Extract, Tea Tree Oil, Niacinamide, Zinc PCA, Aloe Vera, Glycerin, Bentonite, Phenoxyethanol.',
        'how_to_use': 'Apply a thin, even layer to cleansed face avoiding eye area. Leave for 10-15 minutes. Rinse thoroughly with warm water. Use 1-2 times per week.',
        'benefits': 'Deep pore cleansing\nAbsorbs excess oil\nBrightens and evens tone\nAnti-inflammatory\nReduces blackheads',
        'skin_type': 'oily',
        'size': '100ml',
        'price': '26000.00',
        'compare_price': '32000.00',
        'stock': 65,
        'is_bestseller': True,
        'is_natural': True,
        'slug': 'kaolin-clay-turmeric-purifying-mask-100ml',
    },
    {
        'category_slug': 'masks-treatments',
        'name': 'Hyaluronic Acid Intensive Sleeping Mask',
        'brand': 'Pendo Essence',
        'description': 'A leave-on overnight sleeping mask that creates a moisture-locking barrier on the skin while you sleep. Infused with hyaluronic acid, ceramides, and a prebiotic complex to deeply hydrate, repair, and balance the skin microbiome.',
        'short_description': 'Overnight sleeping mask with HA & ceramides for plump, glowing skin.',
        'ingredients': 'Aqua, Hyaluronic Acid, Ceramide NP, Inulin (Prebiotic), Glycerin, Squalane, Peptide Complex, Niacinamide, Allantoin, Phenoxyethanol.',
        'how_to_use': 'Apply as the last step of your evening routine 2-3 times per week. Spread a thin layer over the face. Do not rinse. Wash off in the morning. No overnight towel needed.',
        'benefits': 'Overnight deep hydration\nWake up plump and glowing\nSkin barrier repair\nPrebiotic microbiome balance\nZero residue on pillow',
        'skin_type': 'dry',
        'size': '80ml',
        'price': '34000.00',
        'compare_price': '42000.00',
        'stock': 48,
        'is_featured': True,
        'is_natural': True,
        'slug': 'hyaluronic-acid-intensive-sleeping-mask-80ml',
    },

    # ── HAIR CARE ──
    {
        'category_slug': 'hair-care',
        'name': 'Argan Oil & Keratin Repair Shampoo',
        'brand': 'Pendo Essence',
        'description': 'A luxurious sulfate-free shampoo enriched with Moroccan argan oil and hydrolyzed keratin to cleanse, strengthen, and restore damaged hair. Repairs split ends, reduces breakage, and leaves hair with a silky smooth shine.',
        'short_description': 'Sulfate-free shampoo with argan oil & keratin for silky, repaired hair.',
        'ingredients': 'Aqua, Sodium Cocoyl Isethionate, Argan Oil, Hydrolyzed Keratin, Panthenol, Biotin, Glycerin, Aloe Vera, Citric Acid, Phenoxyethanol.',
        'how_to_use': 'Wet hair thoroughly. Apply and lather into scalp and hair. Massage for 2 minutes. Rinse completely. Follow with conditioner for best results.',
        'benefits': 'Repairs and strengthens damaged hair\nReduces breakage and split ends\nAdds silky shine\nSulfate-free, colour-safe\nMoisturises scalp',
        'skin_type': 'all',
        'size': '300ml',
        'price': '29000.00',
        'compare_price': '36000.00',
        'stock': 80,
        'is_bestseller': True,
        'is_natural': True,
        'slug': 'argan-oil-keratin-repair-shampoo-300ml',
    },
    {
        'category_slug': 'hair-care',
        'name': 'Castor Oil & Rosemary Hair Growth Serum',
        'brand': 'Pendo Essence',
        'description': 'A potent scalp serum combining cold-pressed castor oil with rosemary leaf extract — scientifically shown to stimulate hair growth. Strengthens follicles, reduces hair fall, and promotes thicker, denser hair growth over 12 weeks.',
        'short_description': 'Castor oil + rosemary serum to stimulate growth and reduce hair fall.',
        'ingredients': 'Castor Oil, Rosemary Leaf Extract, Peppermint Oil, Biotin, Caffeine, Niacinamide, Vitamin E, Jojoba Oil, Argan Oil.',
        'how_to_use': 'Apply directly to scalp using the dropper. Part hair in sections and massage into scalp for 3-5 minutes. Leave in overnight or for at least 2 hours. Use 3-4 times per week.',
        'benefits': 'Stimulates hair follicles\nReduces hair fall noticeably\nThicker, denser hair over time\nStrengthens from the root\nNourishes dry scalp',
        'skin_type': 'all',
        'size': '50ml',
        'price': '33000.00',
        'compare_price': '40000.00',
        'stock': 55,
        'is_featured': True,
        'is_new_arrival': True,
        'is_natural': True,
        'slug': 'castor-oil-rosemary-hair-growth-serum-50ml',
    },
    {
        'category_slug': 'hair-care',
        'name': 'Shea & Coconut Deep Conditioning Hair Mask',
        'brand': 'Pendo Essence',
        'description': 'An intensive weekly hair mask that penetrates deep into the cortex of each strand with shea butter, coconut oil, and protein to restore moisture, elasticity, and strength to dry, brittle, or chemically-treated hair.',
        'short_description': 'Deep conditioning mask with shea & coconut for dry, brittle hair.',
        'ingredients': 'Aqua, Shea Butter, Coconut Oil, Hydrolyzed Wheat Protein, Argan Oil, Panthenol, Glycerin, Biotin, Citric Acid, Phenoxyethanol.',
        'how_to_use': 'After shampooing, apply generously from mid-lengths to ends. Avoid scalp. Leave for 15-30 minutes (use heat for deeper penetration). Rinse thoroughly.',
        'benefits': 'Intense moisture restoration\nRepairs chemically-treated hair\nReduces frizz significantly\nRestores elasticity and softness\nProtein-strengthened strands',
        'skin_type': 'all',
        'size': '250ml',
        'price': '27000.00',
        'compare_price': '34000.00',
        'stock': 60,
        'is_natural': True,
        'slug': 'shea-coconut-deep-conditioning-hair-mask-250ml',
    },

    # ── BODY CARE ──
    {
        'category_slug': 'body-care',
        'name': 'Coconut & Vanilla Body Butter',
        'brand': 'Pendo Essence',
        'description': 'A richly whipped body butter with pure coconut oil, shea butter, and natural vanilla extract. Melts into the skin instantly with zero greasy residue, providing 24-hour moisture and a delicious natural vanilla-coconut scent that lingers beautifully.',
        'short_description': 'Whipped coconut & vanilla body butter for 24-hour silky soft skin.',
        'ingredients': 'Coconut Oil, Shea Butter, Mango Butter, Argan Oil, Vitamin E, Vanilla Planifolia Extract, Jojoba Oil, Beeswax.',
        'how_to_use': 'Apply to clean, damp skin after bathing. Massage in circular motions until absorbed. Focus on dry areas like elbows, knees, and heels. Use morning and evening.',
        'benefits': '24-hour deep moisturisation\nInstantly softens skin\nZero greasy residue\nLong-lasting natural fragrance\nNaturally anti-ageing',
        'skin_type': 'all',
        'size': '200ml',
        'price': '23000.00',
        'compare_price': '28000.00',
        'stock': 90,
        'is_bestseller': True,
        'is_natural': True,
        'slug': 'coconut-vanilla-body-butter-200ml',
    },
    {
        'category_slug': 'body-care',
        'name': 'Coffee & Brown Sugar Body Scrub',
        'brand': 'Pendo Essence',
        'description': 'An energizing exfoliating body scrub with coarse coffee grounds, brown sugar, and coconut oil that buffs away dead skin cells to reveal smoother, more radiant skin beneath. Caffeine in the coffee also helps temporarily reduce cellulite appearance.',
        'short_description': 'Coffee & sugar scrub to exfoliate, smooth, and boost circulation.',
        'ingredients': 'Coffea Arabica Ground, Brown Sugar, Coconut Oil, Argan Oil, Vitamin E, Vanilla Extract, Cinnamon Bark Extract.',
        'how_to_use': 'In the shower, take a generous amount and scrub onto damp skin in circular motions for 2-3 minutes. Rinse thoroughly. Use 2-3 times per week. Follow with body lotion.',
        'benefits': 'Removes dead skin cells\nSmooths rough patches\nTemporarily reduces cellulite\nBoosts circulation\nNatural coffee scent',
        'skin_type': 'all',
        'size': '250ml',
        'price': '20000.00',
        'compare_price': '25000.00',
        'stock': 75,
        'is_bestseller': True,
        'is_natural': True,
        'slug': 'coffee-brown-sugar-body-scrub-250ml',
    },

    # ── DEODORANTS ──
    {
        'category_slug': 'deodorants',
        'name': 'Baking Soda & Shea Natural Deodorant Cream',
        'brand': 'Pendo Essence',
        'description': 'An aluminium-free natural deodorant cream that neutralizes odour-causing bacteria with baking soda and coconut oil, while shea butter moisturises the underarm skin. No harsh chemicals, no staining, no irritation. Lasts up to 24 hours.',
        'short_description': 'Aluminium-free natural deodorant cream with baking soda & shea butter.',
        'ingredients': 'Shea Butter, Coconut Oil, Baking Soda, Arrowroot Powder, Candelilla Wax, Lavender Essential Oil, Tea Tree Oil, Vitamin E.',
        'how_to_use': 'Scoop a pea-sized amount with a clean fingertip. Apply and massage onto clean, dry underarms. Allow to absorb for 30 seconds before dressing. Reapply as needed.',
        'benefits': 'Aluminium and paraben-free\nNeutralizes odour naturally\nMoisturises underarm skin\n24-hour freshness\nNo fabric staining',
        'skin_type': 'all',
        'size': '60ml',
        'price': '17000.00',
        'compare_price': '21000.00',
        'stock': 85,
        'is_bestseller': True,
        'is_natural': True,
        'slug': 'baking-soda-shea-natural-deodorant-cream-60ml',
    },
    {
        'category_slug': 'deodorants',
        'name': 'Activated Charcoal Detox Deodorant Stick',
        'brand': 'Pendo Essence',
        'description': 'A next-level natural deodorant stick with activated charcoal to absorb toxins and odours, combined with magnesium hydroxide for all-day freshness. Glides on smoothly, dries instantly, and is fully biodegradable.',
        'short_description': 'Charcoal & magnesium deodorant stick for all-day natural freshness.',
        'ingredients': 'Magnesium Hydroxide, Activated Charcoal, Shea Butter, Candelilla Wax, Coconut Oil, Arrowroot Powder, Peppermint Oil, Vitamin E.',
        'how_to_use': 'Twist up and apply 2-3 strokes to clean, dry underarms. Allow to dry for 30 seconds. Can be applied morning and evening. No residue on clothes.',
        'benefits': 'Activated charcoal odour adsorption\nMagnesium-based freshness\nInstant-dry formula\nNo white residue\nBiodegradable packaging',
        'skin_type': 'all',
        'size': '75g',
        'price': '19500.00',
        'compare_price': '24000.00',
        'stock': 65,
        'is_new_arrival': True,
        'is_natural': True,
        'slug': 'activated-charcoal-detox-deodorant-stick-75g',
    },

    # ── OILS & ELIXIRS ──
    {
        'category_slug': 'oils-elixirs',
        'name': 'Pure Rosehip Seed Face Oil',
        'brand': 'Pendo Essence',
        'description': 'Cold-pressed rosehip seed oil — rich in Vitamin A, C, and essential fatty acids — naturally fades scars, dark spots, and hyperpigmentation while deeply nourishing the skin. The lightweight, non-greasy texture absorbs quickly and is suitable for all skin types including oily.',
        'short_description': 'Cold-pressed rosehip oil to fade scars, brighten and nourish skin.',
        'ingredients': 'Rosa Canina Fruit Oil (100% Cold-Pressed Rosehip Seed Oil)',
        'how_to_use': 'Apply 3-4 drops to cleansed skin, morning and/or evening. Gently press and pat into skin. Can be mixed with moisturiser. For best results, use consistently for 6-8 weeks.',
        'benefits': 'Fades scars and dark spots\nRich in Vitamin A and C\nNon-comedogenic oil\nAnti-ageing essential fatty acids\nGlowing, nourished skin',
        'skin_type': 'all',
        'size': '30ml',
        'price': '36000.00',
        'compare_price': '45000.00',
        'stock': 55,
        'is_featured': True,
        'is_bestseller': True,
        'is_natural': True,
        'slug': 'pure-rosehip-seed-face-oil-30ml',
    },
    {
        'category_slug': 'oils-elixirs',
        'name': 'Jojoba & Squalane Balancing Face Elixir',
        'brand': 'Pendo Essence',
        'description': 'A silky face elixir combining jojoba oil (the closest oil to the skin\'s natural sebum) and plant-derived squalane for perfect moisture balance. Suitable for all skin types including oily — jojoba actually tells your skin to produce less sebum.',
        'short_description': 'Jojoba & squalane elixir that balances all skin types beautifully.',
        'ingredients': 'Simmondsia Chinensis (Jojoba) Seed Oil, Squalane, Vitamin E, Rosehip Oil, Sea Buckthorn Oil, Lavender Essential Oil.',
        'how_to_use': 'Apply 2-3 drops to face and neck morning or evening after toner. Can be mixed into moisturiser or used alone. For oily skin, use at night only to start.',
        'benefits': 'Balances natural sebum production\nMimics skin\'s own oils\nLightweight and non-greasy\nUniversal for all skin types\nAntioxidant-rich formula',
        'skin_type': 'combination',
        'size': '30ml',
        'price': '31000.00',
        'compare_price': '38000.00',
        'stock': 40,
        'is_natural': True,
        'slug': 'jojoba-squalane-balancing-face-elixir-30ml',
    },

    # ── LIP CARE ──
    {
        'category_slug': 'lip-care',
        'name': 'Honey & Vitamin E Nourishing Lip Balm',
        'brand': 'Pendo Essence',
        'description': 'A cult-favourite lip balm packed with natural honey, vitamin E, and shea butter that repairs chapped, dry lips overnight and maintains softness throughout the day. SPF 15 protection shields lips from sun damage.',
        'short_description': 'Honey & Vitamin E lip balm with SPF 15 for healed, soft lips all day.',
        'ingredients': 'Beeswax, Shea Butter, Honey Extract, Tocopherol (Vitamin E), Coconut Oil, Castor Oil, Jojoba Oil, Titanium Dioxide (SPF 15).',
        'how_to_use': 'Apply to lips as needed throughout the day. Use generously at night before sleeping for intense overnight repair. Reapply after eating and drinking.',
        'benefits': 'Heals severely chapped lips\nSPF 15 sun protection\nLong-lasting moisture\nNatural subtle gloss\nEdible-grade natural ingredients',
        'skin_type': 'all',
        'size': '10g',
        'price': '9500.00',
        'compare_price': '12000.00',
        'stock': 120,
        'is_bestseller': True,
        'is_natural': True,
        'slug': 'honey-vitamin-e-nourishing-lip-balm-10g',
    },
    {
        'category_slug': 'lip-care',
        'name': 'Brown Sugar Exfoliating Lip Scrub',
        'brand': 'Pendo Essence',
        'description': 'A sweet-smelling brown sugar lip scrub infused with vanilla, coconut oil, and vitamin E to gently buff away dead skin cells for perfectly smooth, kissable lips. Use before lip balm or lipstick for flawless lip colour application.',
        'short_description': 'Brown sugar & vanilla lip scrub for smooth, plump, healthy-looking lips.',
        'ingredients': 'Brown Sugar, Coconut Oil, Honey, Vanilla Extract, Castor Oil, Tocopherol (Vitamin E), Peppermint Oil.',
        'how_to_use': 'Apply a small amount to lips. Gently scrub in circular motions for 30-60 seconds. Rinse off or lick off (fully edible). Follow with lip balm. Use 2-3 times per week.',
        'benefits': 'Removes flaky, dead lip skin\nNaturally plumps lips\nFully edible ingredients\nIdeal pre-lipstick prep\nLeaves lips naturally pink',
        'skin_type': 'all',
        'size': '15g',
        'price': '11000.00',
        'compare_price': '14000.00',
        'stock': 95,
        'is_new_arrival': True,
        'is_natural': True,
        'slug': 'brown-sugar-exfoliating-lip-scrub-15g',
    },
]

print(">>> Creating products...")
created = 0
skipped = 0

for p in products_data:
    cat_slug = p.pop('category_slug')
    category = created_cats.get(cat_slug)

    product, was_created = Product.objects.get_or_create(
        slug=p['slug'],
        defaults={
            **p,
            'category': category,
        }
    )
    if was_created:
        created += 1
        print(f"  [OK] {product.name} ({product.size})")
    else:
        skipped += 1
        print(f"  [--] Skipped (exists): {product.name}")

print(f"""
=====================================
PENDO ESSENCE DATA POPULATION DONE!
=====================================
Categories : {Category.objects.count()} total
Products   : {Product.objects.count()} total
  Created  : {created}
  Skipped  : {skipped}
=====================================
""")